# Generated by Django 4.0.2 on 2022-02-28 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_empresa_mes_cierre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venc_Imp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('cuit_d', models.IntegerField(default=0)),
                ('cuit_h', models.IntegerField(default=9)),
                ('fecha', models.DateField()),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.impuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Venc_Cli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('fecha', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.empresa')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.impuesto')),
            ],
        ),
    ]
