# Generated by Django 4.0.2 on 2022-03-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vencimientos', '0002_reglavencimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reglavencimiento',
            options={'ordering': ['impuesto', 'dia']},
        ),
    ]
