# Generated by Django 4.0.2 on 2022-02-28 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cuit', models.IntegerField(unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('periodicidad', models.IntegerField(choices=[(1, 'Mensual'), (2, 'Semanal'), (3, 'Quincenal'), (4, 'Trimestral'), (12, 'Anual')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ImpXEmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.empresa')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.impuesto')),
            ],
        ),
        migrations.AddField(
            model_name='impuesto',
            name='empresas',
            field=models.ManyToManyField(through='main.ImpXEmp', to='main.Empresa'),
        ),
    ]
