# Generated by Django 4.0.2 on 2022-02-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cuit',
            field=models.CharField(max_length=11),
        ),
    ]
