# Generated by Django 4.0.2 on 2022-02-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_empresa_cuit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='feriado',
            options={'ordering': ['fecha']},
        ),
        migrations.AlterField(
            model_name='feriado',
            name='fecha',
            field=models.DateField(unique=True),
        ),
    ]
