# Generated by Django 4.0.2 on 2022-02-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_empresa_mes_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='impuesto',
            name='ini_venc',
            field=models.IntegerField(default=10),
        ),
    ]
