# Generated by Django 4.0.2 on 2022-02-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_impuesto_ini_venc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impuesto',
            options={'ordering': ['nombre']},
        ),
    ]
