# Generated by Django 4.0.2 on 2022-03-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_impuesto_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impuesto',
            name='empresas',
        ),
        migrations.AddField(
            model_name='empresa',
            name='impuestos',
            field=models.ManyToManyField(related_name='impuestos_x_empresa', through='main.ImpXEmp', to='main.Impuesto'),
        ),
    ]
